
#pragma once



#undef TAPPING_TOGGLE
#undef RETRO_TAPPING
#undef RETRO_TAPPING_LIMIT
#undef TAPPING_TERM
#undef PERMISSIVE_HOLD
#undef TAPPING_FORCE_HOLD
#undef UNICODE_SELECTED_MODES

#define TAPPING_TOGGLE 1
#define RETRO_TAPPING
#define RETRO_TAPPING_LIMIT 650
#define TAPPING_TERM 100
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD
#define UNICODE_SELECTED_MODES UC_LNX
